
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/dev/protocol/openid-connect/certs
  data:
    mongodb:
      uris:
        - mongodb://root:password@mongodb:27017/operator-fabric?authSource=admin&authMode=scram-sha1

operatorfabric:
  security:
    oauth2:
      client-id: opfab-client
    jwt:
      login-claim: preferred_username
      expire-claim: exp

#here we put urls for all feign clients
users:
  ribbon:
    listOfServers: users:8080
externalRecipients-url: "{\
           api_test_externalRecipient1: \"http://localhost:8090/test\", \
           api_test_externalRecipient2: \"http://localhost:8090/test\" \
           }"