server:
  port: 2102
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    provider-url: http://localhost:89
    provider-realm: dev
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.provider-url}/auth/realms/${spring.security.provider-realm}/protocol/openid-connect/certs
  data:
    mongodb:
      uris:
        - mongodb://root:password@localhost:27017/operator-fabric?authSource=admin&authMode=scram-sha1

security:
  basic:
    enabled: false

operatorfabric:
  security:
    oauth2:
      client-id: opfab-client
    jwt:
      login-claim: preferred_username
      expire-claim: exp

message: common message
management:
  endpoints:
    web:
      exposure:
        include: '*'


#here we put urls for all feign clients
users:
  ribbon:
    listOfServers: http://localhost:2103
externalRecipients-url: "{\
           api_test_externalRecipient1: \"http://localhost:8090/test\", \
           api_test_externalRecipient2: \"http://localhost:8090/test\" \
           }"